version: '3'
services:
  server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_URI=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
